### ISSUE TITLE
Problem wish spectra displayer

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#696] opened 2015-09-01 09:05 UTC
You can zoom correctly in the spectra displayer. In the last version the spectrum disappear.

Testcase: http://visualizer.epfl.ch/tiny/P6EzbVQx0wk76IIZpDaU ([Original URL](http://www.lactame.com/visualizer/v2.22.1/index.html?views=http%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2F8emfrK6dCP%2Ftest%40patiny.com%2FResearch%2FMass%2FPeakWidth%2F.views&results=http%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2FN0nJxtyJE1%2Ftest%40patiny.com%2FResearch%2FMass%2FPeakWidth%2F.results&viewBranch=Master&resultBranch=Master&config=http%3A%2F%2Fscript.epfl.ch%2Fconfigs%2Fhead.json))

**Comment by targos** [comment] 2015-09-01 09:12
I don't have this problem on my side, though jsgraph reports a "programmation error" when I zoom the first time... @NPellet ?

**Comment by targos** [comment] 2015-09-01 09:14
use this link and zoom to see the message: http://www.lactame.com/visualizer/v2.22.1/index.html?viewURL=http://visualizer.epfl.ch/x/P6EzbVQx0wk76IIZpDaU/view.json&dataURL=http://visualizer.epfl.ch/x/P6EzbVQx0wk76IIZpDaU/data.json

**Comment by lpatiny** [comment] 2015-09-01 09:16
This link with the old version. You should check in on head
http://www.lactame.com/visualizer/head/index.html?viewURL=http://visualizer.epfl.ch/x/P6EzbVQx0wk76IIZpDaU/view.json&dataURL=http://visualizer.epfl.ch/x/P6EzbVQx0wk76IIZpDaU/data.json

**Comment by targos** [comment] 2015-09-01 09:17
your OP said last version

**Comment by targos** [comment] 2015-09-01 09:31
OK discard my last message...

To reproduce, open the link on `head`, zoom on x with a small drag. The spectrum should disappear. Then zoom on y with the mousewheel and it will come back

**Comment by NPellet** [comment] 2015-09-01 10:12
Do you still have the programmation error ?
That should have been fixed in the last version of jsGraph already. It was a boundary condition edge case.

**Comment by NPellet** [comment] 2015-09-01 10:37
To be investigated in more details, because I can't replicate the bug.

Please make sure you have the latest version. Also, please give me your series options. Might be be related to that...

Possible to make the data a bit less... heavy ?

**Comment by lpatiny** [comment] 2015-09-01 11:11
Here is a 1D [x,y,x,y,...] file for which we have the problem also:

**Comment by lpatiny** [comment] 2015-09-01 11:11
Should be easier to debug ...

**Comment by lpatiny** [comment] 2015-09-01 11:13
You may see it on
http://visualizer.epfl.ch/tiny/QGHLhSYcGUdgpru3Etvh
Of interest when you zoom the spectrum disappear but if you vertical scale (enough) the spectrum reappears.

**Comment by targos** [comment] 2015-09-01 11:15
@NPellet the programmation error is gone. I'm updating jsgraph to the latest version.

**Comment by targos** [comment] 2015-09-01 11:18
OK looks like it's fixed in 1.13.3-15.
Closing for now, please reopen if the problem comes back

**Closed by targos** 2015-09-01 11:18 UTC
