### ISSUE TITLE
Defaut unit in slick grid unit editor

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#1099] opened 2018-07-08 09:03 UTC
By default if no unit is specified  if should keep the current unit and it there is no current unit and there is a base the base is used as unit

**Comment by stropitek** [comment] 2018-07-08 12:36
yes makes sense

**Comment by stropitek** [comment] 2018-07-08 13:17
duplicate of #1101 ?

**Closed** 2018-07-08 14:42 UTC
