### ISSUE TITLE
duplicate cheminfo view into personal account

### ISSUE THREAD

**Issue by jwist** [NPellet/visualizer#464] opened 2015-03-23 16:55 UTC
It would be nice to be able to duplicate a view from cheminfo into ones personal account in order to modify it, like a "save as" option. I think it is easier to start from existing view and modify it rather than to create a new one from scratch.

Jul

**Comment by lpatiny** [comment] 2015-03-23 16:57
duplicate of #397

**Closed by lpatiny** 2015-03-23 16:57 UTC
