### ISSUE TITLE
Move modules in a given layer and show bars in a spectra displayer

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#663] opened 2015-07-31 07:16 UTC
I have 3 layers in my view (Default, Hidden and Histogram), when I switch between the default and Hidden it works ok, but when I hit the histogram layer, I can't move any module in any layer.

The other one is when I print a histogram in the spectra displayer, it doesn't show the first element of the array that I pass to the spectra module.

Testcase: http://visualizer.epfl.ch/tiny/SAeeAFSDq5FPmo1SnzDe ([Original URL](http://visualizer.epfl.ch/c/home/index.html?viewURL=%2Fc%2F322d373f937cb95a6706334d604a99b1%2Fview.json))

**Comment by targos** [comment] 2015-07-31 08:10
for the first issue, see #432
for the second one, I think it is a jsgraph problem. @NPellet can you look at it ? http://visualizer.epfl.ch/tiny/YAqAKynj7Y2nMMk4FTEu

**Comment by targos** [comment] 2015-08-03 10:53
@JeffersonH44 You don't see the first element because it has a height of 0. You need to force the Y axis to a value, for example 0 and it will appear.

Ref: https://github.com/NPellet/jsGraph/issues/49

**Comment by targos** [comment] 2015-08-03 10:54
I'm closing this since the jsgraph problem is solved and the layer one is a duplicate of #432

**Closed by targos** 2015-08-03 10:54 UTC
