### ISSUE TITLE
Layout problems in global preferences

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#413] opened 2015-03-02 09:55 UTC
On several panels the editor span on the right on the dialog box

Testcase: http://visualizer.epfl.ch/tiny/ihW4VC357573JnGEBNHK ([Original URL](http://www.lactame.com/visualizer/src/index.html))

**Comment by targos** [comment] 2015-03-02 09:59
I cannot reproduce this

2015-03-02 10:55 GMT+01:00 visualizer-feedback <notifications@github.com>:

**Comment by lpatiny** [comment] 2015-03-02 10:01
Only on head seems so:

http://www.lactame.com/visualizer/head/index.html?viewURL=http://visualizer.epfl.ch/x/ihW4VC357573JnGEBNHK/view.json&dataURL=http://visualizer.epfl.ch/x/ihW4VC357573JnGEBNHK/data.json <http://www.lactame.com/visualizer/head/index.html?viewURL=http://visualizer.epfl.ch/x/ihW4VC357573JnGEBNHK/view.json&dataURL=http://visualizer.epfl.ch/x/ihW4VC357573JnGEBNHK/data.json>

**Comment by targos** [comment] 2015-03-02 14:07
fixed by 080e764589a0e67de17b34faf6070c4bf07f445e

**Closed by targos** 2015-03-02 14:07 UTC
