### ISSUE TITLE
Would it be possible to add dynamically modules ?

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#367] opened 2015-02-20 08:01 UTC
It would be nice that in the general preferences of a view we could specify URL of modules that would then be loaded dynamically.

It would allow to have separate project for some specific or private modules that could be build automatically (or not) on lactame.com like we do for libraries.
 

Testcase: http://visualizer.epfl.ch/tiny/iYHONrcrM0Fp1bI2YgAY ([Original URL](http://visualizer.epfl.ch/c/home/index.html))

**Comment by targos** [comment] 2015-02-23 10:52
That requires some work but it is definitely possible

**Comment by stropitek** [comment] 2015-04-08 07:49
Duplicate of #456

**Closed by stropitek** 2015-04-08 07:49 UTC
Labels: core, duplicate, enhancement
