### ISSUE TITLE
spectra displayer strange behaviour

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#878] opened 2016-05-13 14:54 UTC
https://visualizer.epfl.ch/tiny/LRthDGHoewaR9y146jTa

If you look at this view the spectra looks correct.

Now change the last value of the array

var peak = [1,1,5,1,4,2];

(2 instead of 1)

The peaks are now combined.

But if you force the Y axe this does not happen

**Comment by targos** [comment] 2016-05-13 15:28
duplicate of https://github.com/NPellet/jsGraph/issues/76

**Comment by NPellet** [comment] 2016-05-13 15:28
Yep, it's the same effect.

**Comment by targos** [comment] 2016-05-13 15:30
@lpatiny would it work for you if I added an option to the module to force the Y axes to be aligned at 0 ?

**Comment by lpatiny** [comment] 2016-05-13 15:44
If it solves the problem yes it is ok for me.

**Comment by NPellet** [comment] 2016-05-13 16:43
But that cannot be a general rule for the spectra displayer

**Comment by targos** [comment] 2016-05-23 13:55
@lpatiny please try with the latest HEAD

**Comment by lpatiny** [comment] 2016-05-23 14:02
I tried on
https://www.lactame.com/visualizer/HEAD/index.html?v=HEAD&viewURL=https://visualizer.epfl.ch/x/LRthDGHoewaR9y146jTa/view.json&dataURL=https://visualizer.epfl.ch/x/LRthDGHoewaR9y146jTa/data.json

But the result seems still strange and I get also an error in the console

![image](https://cloud.githubusercontent.com/assets/1484241/15473333/c2dca724-20ff-11e6-89f6-ce98aa3f6412.png)

**Comment by targos** [comment] 2016-05-23 14:17
why is it strange ? all the points are supposed to be at 1

**Comment by targos** [comment] 2016-05-23 14:19
btw you should use API.createData in this case. I saw in a lot of views that you use the `set()` function but this is only useful to export a jpath of the value.

**Comment by lpatiny** [comment] 2016-05-23 14:44
OK thanks. I was too fast testing and it seems to work correctly !
I do indeed the "set()" because I thought it was the best way to have variableIn - variableOut in the codeExecutor but API.createData() is easier.
Is this really the way we want to advertise ?

**Comment by targos** [comment] 2016-05-23 14:49
I think we should advertise the API methods more, yes

**Closed by targos** 2016-05-23 14:49 UTC
Labels: bug, M-spectra-displayer
