### ISSUE TITLE
Edit meta data in couch DB button

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#369] opened 2015-02-20 21:57 UTC
In rich text editor, the selection of the style / format fails

I receive an empty select drop down menu

Testcase: http://visualizer.epfl.ch/tiny/6RI1eiOCnoOdomlW2Uj2 ([Original URL](http://visualizer.epfl.ch/c/home/index.html?viewURL=%2Fc%2Fd9bd75989166b0459041ad75bb69c190%2Fview.json))

**Comment by stropitek** [comment] 2015-02-23 13:39
Cannot reproduce...

**Comment by lpatiny** [comment] 2015-02-23 13:48
I can

**Comment by targos** [comment] 2015-02-23 14:26
It is a general bug with the forms component. I'll look into it

**Comment by targos** [comment] 2015-02-24 08:55
fixed with jquery-ui update

**Closed by targos** 2015-02-24 08:55 UTC
