### ISSUE TITLE
bug in slick grid

### ISSUE THREAD

**Issue by bitmorse** [NPellet/visualizer#729] opened 2015-10-15 18:17 UTC
Testcase: http://visualizer.epfl.ch/tiny/hsZBonqyouyjtycihilj ([Original URL](http://www.cheminfo.org/static/index.html?v=v2.28.3&viewURL=http%3A%2F%2Fwww.cheminfo.org%2Fclp%2Fc%2F766371c949ba91421b91915a7b65a975%2Fview.json))

**Comment by stropitek** [comment] 2015-10-16 06:43
Could you please describe?

**Comment by stropitek** [comment] 2015-10-16 06:54
ok, I see what the problem is

**Comment by stropitek** [comment] 2015-10-16 06:58
Fixed in 287fcd187fcaabc05d7b86680df8bd8be4213066

**Closed by stropitek** 2015-10-16 06:58 UTC
