### ISSUE TITLE
replication issue

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#703] opened 2015-09-10 09:30 UTC
i cannot replicate couchdb on local cheminfo.

Testcase: http://visualizer.epfl.ch/tiny/sdOd8AAhpdt9uQLzktP0 ([Original URL](http://www.cheminfo.org/static/index.html?dataURL=http%3A%2F%2Fcouch.cheminfo.org%2Fcheminfo%2F5dc37671c90094f5255872aa98ec3ea2%2Fdata.json%3Frev%3D38-3ff2e726b6d63d6513a847b81c9b10f5&viewURL=http%3A%2F%2Fwww.cheminfo.org%2Fclp%2Fc%2F766371c949ba91421b91915a7b478255%2Fview.json%3Frev%3D1-e2939eac6741e01c936775c7e4f545f6))

**Comment by stropitek** [comment] 2015-09-10 14:01
Duplicate of #702

**Closed by stropitek** 2015-09-10 14:01 UTC
