### ISSUE TITLE
Allow to specify variable that have to be present in Export Data

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#508] opened 2015-04-22 11:57 UTC
Current from a text file and generate an array and a chart that contains the same data.
This means I have
experimentalText
experimental (an array)
experimentalChart (to display the chart)

The 2 last one could be quickly regenerate from the first file. However when exporting data in share view or getData the 3 variables will be exported.

Would be nice in the general preferences to give the possibility to have a checkBox that allows to specify if the variable will be exported or not. Don't know exactly how to do it ...

**Comment by stropitek** [comment] 2015-08-03 14:56
Duplicate of #564

**Closed by stropitek** 2015-08-03 14:56 UTC
Labels: core, enhancement, H-share-view
