### ISSUE TITLE
spectradisplayer and missing horizontal legend

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#897] opened 2016-06-03 09:16 UTC
Don't understand why the horizontal axe legend is not being displayed in the view:

(just draw anything and click Calculate spectrum)

In the preferences it should be 'δ (ppm)'

It seems that when the input variable is jcamp the label is not set but only in the case of chart. Should not label not be added independently of the input variable kind ?

**Comment by targos** [comment] 2016-06-03 13:26
the link is missing

**Comment by lpatiny** [comment] 2016-06-03 13:29
http://www.cheminfo.org/Spectra/NMR/Predictions/1H_Prediction/index.html?viewURL=https%3A%2F%2Fcouch.cheminfo.org%2Fcheminfo-public%2Feea0ba081ea2cc99da5c1aed2f29a0a8%2Fview.json%3Frev%3D15-f0e85716b4d23a2b54b44759f1047cf5

**Comment by targos** [comment] 2016-06-03 13:34
The label disappears when the axis is flipped. CC @NPellet

**Comment by NPellet** [comment] 2016-06-03 17:44
oh... ok

**Comment by NPellet** [comment] 2016-06-03 17:55
ok should be fixed

**Comment by targos** [comment] 2016-06-06 08:50
confirmed, thanks

**Comment by lpatiny** [comment] 2016-06-10 05:42
Is it really fixed ?

https://my.cheminfo.org/?viewURL=https%3A%2F%2Fmydb.cheminfo.org%2Fdb%2Fvisualizer%2Fentry%2F4b7669c5ec0a15e6fb3994f53b950277%2Fview.json&v=HEAD

**Comment by targos** [comment] 2016-06-10 06:32
yes it is

**Closed by targos** 2016-06-10 06:32 UTC
Labels: bug, M-spectra-displayer

**Comment by NPellet** [comment] 2016-06-10 06:39
Something to mention is that I changed the way the horizontal legend is
calculated, because with the previous fix it didn't work with axis spanning.

So maybe I reintroduced the bug...

2016-06-10 8:32 GMT+02:00 Michaël Zasso <notifications@github.com>:

**Comment by targos** [comment] 2016-06-10 08:07
@NPellet it's fine. There was a build issue on our server
