### ISSUE TITLE
Plotter highlight is chaotic

### ISSUE THREAD

**Issue by otrobernal** [NPellet/visualizer#334] opened 2015-01-19 00:56 UTC
Highlight in the plotter module is somewhat chaotic and does not search entries in a slick table. Test link:
http://visualizer.epfl.ch/tiny/33OZ3OE9U0YDvTPvhJQh

**Comment by stropitek** [comment] 2015-07-27 14:23
Duplicate of #477

**Closed by stropitek** 2015-07-27 14:23 UTC
Labels: bug, module
